vm.swappiness = 10
vm.vfs_cache_pressure = 100
vm.page-cluster = 1
vm.dirty_ratio = 40
vm.dirty_background_ratio = 10
vm.compaction_proactiveness = 0

net.core.default_qdisc = cake
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_mtu_probing = 1
net.ipv4.tcp_slow_start_after_idle = 0

kernel.nmi_watchdog = 0
