[mgr]
prepend_keymap = [
  { on = ["g", "u"], run = "cd ~/Uni-Data/Sem-IV", desc = "Go to Sem Data" },
  { on = "u", run = "plugin restore", desc = "Restore last deleted files/folders" },
  { on   = [ "c", "a", "a" ], run  = "plugin compress", desc = "Archive selected files" },
  { on   = [ "c", "a", "p" ], run  = "plugin compress -p", desc = "Archive selected files (password)"},
  { on   = [ "c", "a", "h" ], run  = "plugin compress -ph", desc = "Archive selected files (password+header)" },
  { on   = [ "c", "a", "u" ], run  = "plugin compress -phl", desc = "Archive selected files (password+header+level)" },
  { on   =  "z", run  = "plugin zip-input", desc = "Zip selected files" },
  # or use "d + u" like me
  # { on = ["d", u"], run = "plugin restore", desc = "Restore last deleted files/folders" },

  # Select files/folders to restore. Input item index or range separated by comma:
  # - Restore a trashed file:
  #      What file to restore [0..4]: 4
  # - Restore multiple trashed files separated by comma, also support range:
  #      What file to restore [0..3]: 0-2, 3

  # This will throw error when there is existed file/folder
  { on = [ "U" ], run = "plugin restore -- --interactive", desc = "Restore deleted files/folders (Interactive)" },
  # Or auto overwrite existed file/folder
  # { on = [ "U" ], run = "plugin restore -- --interactive --interactive-overwrite", desc = "Restore deleted files/folders (Interactive overwrite)" },
  ]
[input]
prepend_keymap = [
  { on = "<Esc>", run = "close", desc = "Cancel input" },
]
