[opener]
edit = [
  { run = 'nvim %0', block = true, desc = "Neovim", for = "unix" },
  { run = 'code %0', desc = "Code", for = "unix" },
]
play = [
  { run = 'mpv %0', for = "unix" },
]
open = [
	{ run = "xdg-open %01", desc = "Open" },
    { run = "nvim .", block = true, desc = "Neovim (PWD)" },
    { run = "code .", block = true, desc = "Code (PWD)" },
]
dir = [
  { run = 'sh -c "cd \"$1\" && nvim " -- "" "%0"', desc = "Neovim", block = true, for = "unix" },
  { run = '"$0"code %0', desc = "Code", for = "unix" },
]

[open]
append_rules = [
  { url = "*/", use = [ "dir", "open" ] },
  { mime = "audio/*", use = "play" },
  { mime = "video/*", use = "play" },
  { url = "*", use = [ "edit", "open" ]},
]

[mgr]
ratio = [0, 2, 1]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
